import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { 
  ArrowLeft, MapPin, Plus, Clock, Zap, ChevronRight, 
  CreditCard, Smartphone, Banknote, Check, ShieldCheck,
  Package, Loader2
} from 'lucide-react';
import { useCartStore } from '@/stores/cartStore';
import { useLocationStore } from '@/stores/locationStore';
import { useDeliveryEta } from '@/hooks/useDeliveryEta';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { DbAddress } from '@/lib/supabase-types';
import { toast } from 'sonner';

type PaymentMethod = 'upi' | 'card' | 'cod';
type Step = 'review' | 'address' | 'payment' | 'success';

const Checkout = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { 
    items, clearCart, getSubtotal, getSavings, getDiscount, 
    getDeliveryFee, getTotal, appliedCoupon 
  } = useCartStore();
  const { nearestStore, selectedLocation } = useLocationStore();
  const eta = useDeliveryEta();
  
  const [step, setStep] = useState<Step>('review');
  const [addresses, setAddresses] = useState<DbAddress[]>([]);
  const [selectedAddress, setSelectedAddress] = useState<DbAddress | null>(null);
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('cod');
  const [isLoading, setIsLoading] = useState(false);
  const [orderId, setOrderId] = useState<string | null>(null);
  const [showAddAddress, setShowAddAddress] = useState(false);
  const [newAddress, setNewAddress] = useState({
    flat_number: '',
    building: '',
    street: '',
    area: selectedLocation?.name || '',
    pincode: '',
    landmark: '',
    label: 'home',
  });

  const subtotal = getSubtotal();
  const savings = getSavings();
  const discount = getDiscount();
  const deliveryFee = getDeliveryFee();
  const total = getTotal();

  useEffect(() => {
    if (!user) {
      navigate('/auth');
      return;
    }

    const fetchAddresses = async () => {
      const { data } = await supabase
        .from('addresses')
        .select('*')
        .eq('user_id', user.id)
        .order('is_default', { ascending: false });

      if (data && data.length > 0) {
        setAddresses(data as DbAddress[]);
        const defaultAddr = data.find((a: DbAddress) => a.is_default) || data[0];
        setSelectedAddress(defaultAddr as DbAddress);
      }
    };

    fetchAddresses();
  }, [user, navigate]);

  const handleAddAddress = async () => {
    if (!user) return;
    
    if (!newAddress.flat_number || !newAddress.building || !newAddress.area || !newAddress.pincode) {
      toast.error('Please fill all required fields');
      return;
    }

    setIsLoading(true);
    const { data, error } = await supabase
      .from('addresses')
      .insert({
        user_id: user.id,
        ...newAddress,
        lat: selectedLocation?.lat,
        lng: selectedLocation?.lng,
        is_default: addresses.length === 0,
      })
      .select()
      .single();

    if (error) {
      toast.error('Failed to add address');
    } else if (data) {
      setAddresses([...addresses, data as DbAddress]);
      setSelectedAddress(data as DbAddress);
      setShowAddAddress(false);
      toast.success('Address added!');
    }
    setIsLoading(false);
  };

  const handlePlaceOrder = async () => {
    if (!user || !selectedAddress || !nearestStore) {
      toast.error('Missing required information');
      return;
    }

    setIsLoading(true);
    try {
      // Create order
      const estimatedDelivery = new Date();
      estimatedDelivery.setMinutes(estimatedDelivery.getMinutes() + eta.minutes);

      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          user_id: user.id,
          store_id: nearestStore.id,
          address_id: selectedAddress.id,
          subtotal: subtotal,
          discount: discount,
          delivery_fee: deliveryFee,
          total: total,
          payment_method: paymentMethod,
          payment_status: paymentMethod === 'cod' ? 'pending' : 'paid',
          estimated_delivery_minutes: eta.minutes,
          estimated_delivery_time: estimatedDelivery.toISOString(),
          order_number: '', // Will be generated by trigger
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = items.map(item => ({
        order_id: order.id,
        product_id: item.product.id,
        product_name: item.product.name,
        product_image: item.product.images?.[0] || null,
        quantity: item.quantity,
        price: Number(item.product.price),
        mrp: Number(item.product.mrp),
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      setOrderId(order.id);
      clearCart();
      setStep('success');
      toast.success('Order placed successfully! 🎉');
    } catch (error) {
      console.error('Order error:', error);
      toast.error('Failed to place order. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const paymentMethods = [
    { id: 'upi', label: 'UPI / PhonePe / GPay', icon: Smartphone, desc: 'Pay using any UPI app' },
    { id: 'card', label: 'Credit / Debit Card', icon: CreditCard, desc: 'Visa, Mastercard, RuPay' },
    { id: 'cod', label: 'Cash on Delivery', icon: Banknote, desc: 'Pay when you receive' },
  ];

  if (items.length === 0 && step !== 'success') {
    navigate('/cart');
    return null;
  }

  return (
    <div className="min-h-screen bg-background pb-32">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-card shadow-card">
        <div className="container py-4 flex items-center gap-4">
          <motion.button
            whileTap={{ scale: 0.9 }}
            onClick={() => {
              if (step === 'review') navigate(-1);
              else if (step === 'address') setStep('review');
              else if (step === 'payment') setStep('address');
            }}
            className="w-10 h-10 rounded-full bg-secondary flex items-center justify-center"
          >
            <ArrowLeft className="w-5 h-5 text-foreground" />
          </motion.button>
          <div>
            <h1 className="text-lg font-bold text-foreground">
              {step === 'review' && 'Order Summary'}
              {step === 'address' && 'Delivery Address'}
              {step === 'payment' && 'Payment'}
              {step === 'success' && 'Order Confirmed'}
            </h1>
            {step !== 'success' && (
              <p className="text-xs text-muted-foreground">
                Step {step === 'review' ? 1 : step === 'address' ? 2 : 3} of 3
              </p>
            )}
          </div>
        </div>
      </header>

      <AnimatePresence mode="wait">
        {/* Step 1: Review */}
        {step === 'review' && (
          <motion.div
            key="review"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="container py-4 space-y-4"
          >
            {/* ETA Banner */}
            <div className="bg-primary/10 rounded-2xl p-4 flex items-center gap-3">
              <div className="w-12 h-12 rounded-full bg-primary/20 flex items-center justify-center">
                <Zap className="w-6 h-6 text-primary" />
              </div>
              <div>
                <p className="font-semibold text-foreground">Delivery in {eta.text}</p>
                <p className="text-sm text-muted-foreground">
                  From {nearestStore?.name || 'SweeftCom Store'}
                </p>
              </div>
            </div>

            {/* Items Summary */}
            <div className="bg-card rounded-2xl shadow-card overflow-hidden">
              <div className="p-4 border-b border-border flex items-center justify-between">
                <h3 className="font-semibold text-foreground">
                  {items.length} Items
                </h3>
                <button 
                  onClick={() => navigate('/cart')}
                  className="text-primary text-sm font-medium"
                >
                  Edit Cart
                </button>
              </div>
              <div className="p-4 max-h-60 overflow-y-auto space-y-3">
                {items.map((item) => (
                  <div key={item.id} className="flex items-center gap-3">
                    <div className="w-12 h-12 rounded-lg bg-muted flex items-center justify-center overflow-hidden">
                      {item.product.images?.[0] ? (
                        <img src={item.product.images[0]} alt="" className="w-full h-full object-cover" />
                      ) : (
                        <Package className="w-6 h-6 text-muted-foreground" />
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-medium text-foreground text-sm line-clamp-1">{item.product.name}</p>
                      <p className="text-xs text-muted-foreground">Qty: {item.quantity}</p>
                    </div>
                    <p className="font-semibold text-foreground">₹{(Number(item.product.price) * item.quantity).toFixed(0)}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Bill Details */}
            <div className="bg-card rounded-2xl p-4 shadow-card space-y-3">
              <h3 className="font-semibold text-foreground">Bill Details</h3>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Item Total</span>
                  <span>₹{subtotal.toFixed(0)}</span>
                </div>
                {savings > 0 && (
                  <div className="flex justify-between text-primary">
                    <span>Product Discount</span>
                    <span>-₹{savings.toFixed(0)}</span>
                  </div>
                )}
                {discount > 0 && (
                  <div className="flex justify-between text-primary">
                    <span>Coupon ({appliedCoupon?.code})</span>
                    <span>-₹{discount.toFixed(0)}</span>
                  </div>
                )}
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Delivery Fee</span>
                  <span className={deliveryFee === 0 ? 'text-primary' : ''}>
                    {deliveryFee === 0 ? 'FREE' : `₹${deliveryFee}`}
                  </span>
                </div>
                <div className="h-px bg-border" />
                <div className="flex justify-between font-bold text-lg">
                  <span>Total</span>
                  <span>₹{total.toFixed(0)}</span>
                </div>
              </div>
            </div>
          </motion.div>
        )}

        {/* Step 2: Address */}
        {step === 'address' && (
          <motion.div
            key="address"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="container py-4 space-y-4"
          >
            {/* Saved Addresses */}
            {addresses.length > 0 && !showAddAddress && (
              <div className="space-y-3">
                <h3 className="font-semibold text-foreground">Select Delivery Address</h3>
                {addresses.map((addr) => (
                  <motion.button
                    key={addr.id}
                    whileTap={{ scale: 0.98 }}
                    onClick={() => setSelectedAddress(addr)}
                    className={`w-full text-left p-4 rounded-2xl border-2 transition-colors ${
                      selectedAddress?.id === addr.id
                        ? 'border-primary bg-primary/5'
                        : 'border-border bg-card'
                    }`}
                  >
                    <div className="flex items-start gap-3">
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center ${
                        selectedAddress?.id === addr.id ? 'bg-primary' : 'bg-secondary'
                      }`}>
                        <MapPin className={`w-5 h-5 ${selectedAddress?.id === addr.id ? 'text-primary-foreground' : 'text-foreground'}`} />
                      </div>
                      <div className="flex-1">
                        <p className="font-semibold text-foreground capitalize">{addr.label}</p>
                        <p className="text-sm text-muted-foreground">
                          {addr.flat_number}, {addr.building}, {addr.street}
                        </p>
                        <p className="text-sm text-muted-foreground">
                          {addr.area}, {addr.city} - {addr.pincode}
                        </p>
                      </div>
                      {selectedAddress?.id === addr.id && (
                        <Check className="w-5 h-5 text-primary" />
                      )}
                    </div>
                  </motion.button>
                ))}
              </div>
            )}

            {/* Add New Address Button */}
            {!showAddAddress && (
              <motion.button
                whileTap={{ scale: 0.98 }}
                onClick={() => setShowAddAddress(true)}
                className="w-full p-4 rounded-2xl border-2 border-dashed border-primary/50 bg-primary/5 flex items-center gap-3"
              >
                <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center">
                  <Plus className="w-5 h-5 text-primary" />
                </div>
                <span className="font-semibold text-primary">Add New Address</span>
              </motion.button>
            )}

            {/* Add Address Form */}
            {showAddAddress && (
              <div className="bg-card rounded-2xl p-4 shadow-card space-y-4">
                <h3 className="font-semibold text-foreground">Add New Address</h3>
                <div className="grid gap-4">
                  <div className="grid grid-cols-2 gap-3">
                    <input
                      placeholder="Flat/House No.*"
                      value={newAddress.flat_number}
                      onChange={(e) => setNewAddress({ ...newAddress, flat_number: e.target.value })}
                      className="p-3 rounded-xl bg-secondary text-foreground placeholder:text-muted-foreground outline-none"
                    />
                    <input
                      placeholder="Building Name*"
                      value={newAddress.building}
                      onChange={(e) => setNewAddress({ ...newAddress, building: e.target.value })}
                      className="p-3 rounded-xl bg-secondary text-foreground placeholder:text-muted-foreground outline-none"
                    />
                  </div>
                  <input
                    placeholder="Street/Road"
                    value={newAddress.street}
                    onChange={(e) => setNewAddress({ ...newAddress, street: e.target.value })}
                    className="p-3 rounded-xl bg-secondary text-foreground placeholder:text-muted-foreground outline-none"
                  />
                  <div className="grid grid-cols-2 gap-3">
                    <input
                      placeholder="Area*"
                      value={newAddress.area}
                      onChange={(e) => setNewAddress({ ...newAddress, area: e.target.value })}
                      className="p-3 rounded-xl bg-secondary text-foreground placeholder:text-muted-foreground outline-none"
                    />
                    <input
                      placeholder="Pincode*"
                      value={newAddress.pincode}
                      onChange={(e) => setNewAddress({ ...newAddress, pincode: e.target.value })}
                      className="p-3 rounded-xl bg-secondary text-foreground placeholder:text-muted-foreground outline-none"
                    />
                  </div>
                  <input
                    placeholder="Landmark (optional)"
                    value={newAddress.landmark}
                    onChange={(e) => setNewAddress({ ...newAddress, landmark: e.target.value })}
                    className="p-3 rounded-xl bg-secondary text-foreground placeholder:text-muted-foreground outline-none"
                  />
                  <div className="flex gap-2">
                    {['home', 'work', 'other'].map((label) => (
                      <button
                        key={label}
                        onClick={() => setNewAddress({ ...newAddress, label })}
                        className={`px-4 py-2 rounded-lg text-sm font-medium capitalize ${
                          newAddress.label === label
                            ? 'bg-primary text-primary-foreground'
                            : 'bg-secondary text-foreground'
                        }`}
                      >
                        {label}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="flex gap-3">
                  <button
                    onClick={() => setShowAddAddress(false)}
                    className="flex-1 py-3 rounded-xl bg-secondary text-foreground font-semibold"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleAddAddress}
                    disabled={isLoading}
                    className="flex-1 py-3 rounded-xl bg-primary text-primary-foreground font-semibold flex items-center justify-center gap-2"
                  >
                    {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : 'Save Address'}
                  </button>
                </div>
              </div>
            )}

            {/* Delivery ETA */}
            {selectedAddress && (
              <div className="bg-secondary/50 rounded-2xl p-4 flex items-center gap-3">
                <Clock className="w-5 h-5 text-primary" />
                <div>
                  <p className="font-medium text-foreground">Estimated Delivery: {eta.text}</p>
                  <p className="text-sm text-muted-foreground">
                    To {selectedAddress.area}
                  </p>
                </div>
              </div>
            )}
          </motion.div>
        )}

        {/* Step 3: Payment */}
        {step === 'payment' && (
          <motion.div
            key="payment"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="container py-4 space-y-4"
          >
            <h3 className="font-semibold text-foreground">Select Payment Method</h3>
            
            <div className="space-y-3">
              {paymentMethods.map((method) => (
                <motion.button
                  key={method.id}
                  whileTap={{ scale: 0.98 }}
                  onClick={() => setPaymentMethod(method.id as PaymentMethod)}
                  className={`w-full text-left p-4 rounded-2xl border-2 transition-colors ${
                    paymentMethod === method.id
                      ? 'border-primary bg-primary/5'
                      : 'border-border bg-card'
                  }`}
                >
                  <div className="flex items-center gap-4">
                    <div className={`w-12 h-12 rounded-full flex items-center justify-center ${
                      paymentMethod === method.id ? 'bg-primary' : 'bg-secondary'
                    }`}>
                      <method.icon className={`w-6 h-6 ${paymentMethod === method.id ? 'text-primary-foreground' : 'text-foreground'}`} />
                    </div>
                    <div className="flex-1">
                      <p className="font-semibold text-foreground">{method.label}</p>
                      <p className="text-sm text-muted-foreground">{method.desc}</p>
                    </div>
                    {paymentMethod === method.id && (
                      <Check className="w-5 h-5 text-primary" />
                    )}
                  </div>
                </motion.button>
              ))}
            </div>

            {/* Order Summary */}
            <div className="bg-card rounded-2xl p-4 shadow-card">
              <div className="flex items-center justify-between mb-3">
                <span className="text-muted-foreground">Delivering to</span>
                <span className="font-medium text-foreground capitalize">{selectedAddress?.label}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground">Total Amount</span>
                <span className="font-bold text-lg text-foreground">₹{total.toFixed(0)}</span>
              </div>
            </div>

            <div className="flex items-center justify-center gap-2 text-muted-foreground">
              <ShieldCheck className="w-4 h-4" />
              <span className="text-sm">100% Secure Payments</span>
            </div>
          </motion.div>
        )}

        {/* Success */}
        {step === 'success' && (
          <motion.div
            key="success"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="container py-8 flex flex-col items-center text-center"
          >
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ type: 'spring', delay: 0.2 }}
              className="w-24 h-24 rounded-full bg-primary flex items-center justify-center mb-6"
            >
              <Check className="w-12 h-12 text-primary-foreground" />
            </motion.div>
            <h2 className="text-2xl font-bold text-foreground mb-2">Order Confirmed! 🎉</h2>
            <p className="text-muted-foreground mb-6">
              Your order will be delivered in {eta.text}
            </p>
            <div className="bg-card rounded-2xl p-4 shadow-card w-full max-w-sm mb-6">
              <div className="flex items-center gap-3">
                <Zap className="w-6 h-6 text-primary" />
                <div className="text-left">
                  <p className="font-semibold text-foreground">Delivery from {nearestStore?.name}</p>
                  <p className="text-sm text-muted-foreground">Your order is being prepared</p>
                </div>
              </div>
            </div>
            <button
              onClick={() => navigate('/orders')}
              className="px-8 py-3 rounded-xl bg-primary text-primary-foreground font-semibold"
            >
              Track Order
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Bottom CTA */}
      {step !== 'success' && (
        <div className="fixed bottom-0 left-0 right-0 bg-card border-t border-border p-4 pb-safe">
          <div className="container">
            <div className="flex items-center justify-between mb-2">
              <div>
                <p className="text-sm text-muted-foreground">Total</p>
                <p className="text-xl font-bold text-foreground">₹{total.toFixed(0)}</p>
              </div>
              <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => {
                  if (step === 'review') setStep('address');
                  else if (step === 'address' && selectedAddress) setStep('payment');
                  else if (step === 'payment') handlePlaceOrder();
                }}
                disabled={isLoading || (step === 'address' && !selectedAddress)}
                className="px-8 py-3 rounded-xl bg-primary text-primary-foreground font-semibold flex items-center gap-2 disabled:opacity-50"
              >
                {isLoading ? (
                  <Loader2 className="w-5 h-5 animate-spin" />
                ) : (
                  <>
                    <span>
                      {step === 'review' && 'Select Address'}
                      {step === 'address' && 'Select Payment'}
                      {step === 'payment' && 'Place Order'}
                    </span>
                    <ChevronRight className="w-5 h-5" />
                  </>
                )}
              </motion.button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Checkout;